server:
  port: 8080

# ?????
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.poolDruidDataSoure
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/veadmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: yrO,cl:#x7y8

      # ???????
      initial-size: 5
      # ???????
      min-idle: 5
      max-active: 20
      max-wait: 30000
      # ????????????
      time-between-connect-error-millis: 60000
      # ??????????????
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # ??PSCache??????????PSCache???
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # ?????????filters
      filters: stat

      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  # ?? JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  jackson:
    time-zone: GMT+8

  redis:
    # ?????
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # ?????
        max-active: 100
        # ????????(???????)
        max-wait: 2000
        # ????
        max-idle: 500
        # ????
        min-idle: 8
    # ??????
    timeout: 5000

